/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;

/**
 * Clase que hereda de VentanaInternaMultimedia y que se lanzará cuando la clase
 * VentanaPrincipal requiera el uso de la cámara.
 * @author: Daniel Ruiz Medina
 * @version: 01/06/2021
 */
public class VentanaInternaCamara extends VentanaInternaMultimedia {

    private Webcam camara = null;
    
    /**
     * Constructor que selecciona la cámara por defecto y la sitúa en el 
     * centro de la ventana
     */
    private VentanaInternaCamara() {
        initComponents();
        camara = Webcam.getDefault();
        if (camara != null) {
            WebcamPanel areaVisual = new WebcamPanel(camara);
            if (areaVisual != null) {
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
    }

    /**
     * Método estático utilizando para llamar al constructor privado de dicha 
     * clase, creando la clase y devolviendo la webcam seleccionada.
     * @return (tipo: Webcam) cámara activa.
     */
    public static VentanaInternaCamara getInstance() {
        VentanaInternaCamara v = new VentanaInternaCamara();
        return (v.camara != null ? v : null);
    }
    
    /**
     * Método que devuelve una instantánea(Foto) de la webcam activa.
     * @return (tipo: BufferedImage) foto instantánea de la webcam activa
     */
    @Override
    public BufferedImage getImage(){
        return camara!=null ? camara.getImage() : null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que libera la cámara utilizada cuando se selecciona el botón cerrar
     * de la ventana.
     * @param evt evento lanzador
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (camara != null) {
            camara.close();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    /**
     * Método que modificaría la imagen, no se utiliza pero se implementa 
     * por heredar de una clase abstracta
     * @param imagen que sustituiría la antigua imagen
     */
    @Override
    public void setImage(BufferedImage imagen) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
