/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.awt.image.BufferedImage;

/**
 * Clase abstracta padre utlizada por las demas clases ventanas internas para
 * crear ventanas internas
 * @author: Daniel Ruiz Medina
 * @version: 01/06/2021
 */
public abstract class VentanaInternaMultimedia extends javax.swing.JInternalFrame {

    /**
     * Constructor por defecto que inicializa los componentes de la ventana.
     */
    public VentanaInternaMultimedia() {
        initComponents();
    }

    /**
     * Método que debe ser implementado en la clases hijas para obtener la 
     * imagen del lienzo o cámara
     * @return 
     */
    public abstract BufferedImage getImage();

    /**
     * Método que debe ser implementado en la clases hijas para modificar la 
     * imagen.
     * @param imagen que sustituirá la imagen del lienzo.
     */
    public abstract void setImage(BufferedImage imagen);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
