/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.awt.image.BufferedImage;
import sm.drm.iu.DLienzo2D;

/**
 * Clase que hereda de VentanaInternaMultimedia y que se lanzará cuando la clase
 * VentanaPrincipal requiera el uso de la imágenes.
 * @author: Daniel Ruiz Medina
 * @version: 01/06/2021
 */
public class VentanaInternaImagen extends VentanaInternaMultimedia {

    /**
     * Constructor por defecto que inicializa los componentes de la ventana.
     */
    public VentanaInternaImagen() {
        initComponents();
    }

    /**
     * Método que devuelve el lienzo donde se almacena y operan las imágenes.
     * @return (tipo: DLienzo2D) lienzo de la ventana.
     */
    public DLienzo2D getLienzo2D() {
        return Lienzo2D;
    }

    /**
     * Método que modifica el lienzo donde se almacena y operan las imágenes.
     * @param Lienzo2D nuevo lienzo que sustituirá al antiguo lienzo.
     */
    public void setLienzo2D(DLienzo2D Lienzo2D) {
        this.Lienzo2D = Lienzo2D;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Lienzo2D = new sm.drm.iu.DLienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout Lienzo2DLayout = new javax.swing.GroupLayout(Lienzo2D);
        Lienzo2D.setLayout(Lienzo2DLayout);
        Lienzo2DLayout.setHorizontalGroup(
            Lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        Lienzo2DLayout.setVerticalGroup(
            Lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Lienzo2D);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.drm.iu.DLienzo2D Lienzo2D;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que devuelve la imagen lienzo de la ventana.
     * @return (tipo: BufferedImage) iamgen del lienzo de la ventana.
     */
    @Override
    public BufferedImage getImage() {
        return this.Lienzo2D.getImagen();
    }
    
    /**
     * Método que modifica la imagen del lienzo
     * @param imagen sustituirá la antigua imagen del lienzo.
     */
    @Override
    public void setImage(BufferedImage imagen) {
        this.Lienzo2D.setImagen(imagen);
    }
}
