/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.drm.graficos;

import java.awt.Color;

/**
 * Clase para crear los colores de la lista desplegrable
 *
 * @author: Daniel Ruiz Medina
 * @version: 01/06/2021
 */
public class PanelColor extends javax.swing.JPanel {

    /**
     * Constructor que inicaliza los componentes y establede un color de fondo.
     * @param color color de fondo.
     */
    public PanelColor(Color color) {
        initComponents();
        bColor.setBackground(color);
    }

    /**
     * Modifica el color de fondo
     * @param color nuevo color de fondo.
     */
    public void setColor(Color color){
        bColor.setBackground(color);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bColor = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        bColor.setMaximumSize(new java.awt.Dimension(24, 9));
        bColor.setMinimumSize(new java.awt.Dimension(24, 9));
        add(bColor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bColor;
    // End of variables declaration//GEN-END:variables
}
